"""Assunta app icon: an oscilloscope screen whose traces draw the letter "A".

Channel 1 is a flat trace with a small blip, a tall peak (the legs of the A) and
a damped ringing after it; channel 2 is a smaller bump that crosses the legs
(the crossbar). Both glow with a cyan → violet → magenta gradient.

Writes assunta-icon.svg (1024x1024, tile at 100..924) and prints the two path
strings used by src/components/AssuntaMark.tsx.

Usage: python3 generate_icon.py && rsvg-convert -w 1024 -h 1024 assunta-icon.svg -o assunta-icon-1024.png
"""
import math

BASE = 648.0      # baseline y
APEX = 250.0      # apex y
CX = 512.0        # centre x
HALF = 172.0      # half width of the A at the baseline
X0, X1 = 178.0, 846.0
H = BASE - APEX


def smooth_max0(a, d=0.14):
    return (a + math.sqrt(a * a + d * d)) / 2


def peak(x):
    u = abs(x - CX) / HALF
    soft_abs = math.sqrt(u * u + 0.07 ** 2) - 0.07   # rounded apex
    return smooth_max0(1 - soft_abs) / smooth_max0(1.0)


def channel1(x):
    v = peak(x)
    # small blip before the peak
    v += -0.07 * math.sin(2 * math.pi * (x - 222) / 70) * math.exp(-((x - 240) / 24) ** 2)
    # damped ringing after it: a dip below the baseline, then a smaller bounce
    start = CX + HALF + 8
    if x > start:
        t = x - start
        v += -0.16 * math.sin(2 * math.pi * t / 92) * math.exp(-t / 58)
    return BASE - H * v


def channel2(x):
    return BASE - H * 0.34 * math.exp(-((x - CX) / 96) ** 2)


def path(fn, x0=X0, x1=X1, step=2.0):
    pts = []
    x = x0
    while x <= x1 + 1e-9:
        pts.append((x, fn(x)))
        x += step
    return 'M' + ' L'.join(f'{px:.1f} {py:.1f}' for px, py in pts)


TRACE_A = path(channel1)
TRACE_BAR = path(channel2, 330, 694)

GRID = []
for i in range(1, 8):
    p = 100 + i * 103
    GRID.append(f'M{p} 130V894')
    GRID.append(f'M130 {p}H894')
GRID_D = ' '.join(GRID)

SVG = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <!-- Assunta app icon: oscilloscope traces drawing the letter "A" (generated by generate_icon.py) -->
  <defs>
    <radialGradient id="screen" cx="0.5" cy="0.45" r="0.75">
      <stop offset="0" stop-color="#111827"/>
      <stop offset="1" stop-color="#03050C"/>
    </radialGradient>
    <linearGradient id="trace" gradientUnits="userSpaceOnUse" x1="0" y1="{APEX - 20:.0f}" x2="0" y2="{BASE + 20:.0f}">
      <stop offset="0" stop-color="#22D3EE"/>
      <stop offset="0.55" stop-color="#8B5CF6"/>
      <stop offset="1" stop-color="#EC4899"/>
    </linearGradient>
    <filter id="glow" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="14" result="blur"/>
      <feMerge><feMergeNode in="blur"/><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
  </defs>
  <rect x="100" y="100" width="824" height="824" rx="190" fill="url(#screen)"/>
  <path d="{GRID_D}" stroke="#22D3EE" stroke-opacity="0.09" stroke-width="3" fill="none"/>
  <g fill="none" stroke="url(#trace)" stroke-width="28" stroke-linecap="round" stroke-linejoin="round" filter="url(#glow)">
    <path d="{TRACE_BAR}"/>
    <path d="{TRACE_A}"/>
  </g>
</svg>
'''

if __name__ == '__main__':
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    open(os.path.join(here, 'assunta-icon.svg'), 'w').write(SVG)
    ts = os.path.join(here, '..', '..', '..', 'src', 'components', 'assuntaMarkPaths.ts')
    with open(ts, 'w') as f:
        f.write('// Generated by src-tauri/icons/source/generate_icon.py: the traces of the Assunta mark.\n')
        f.write(f'export const TRACE_A = "{TRACE_A}";\n')
        f.write(f'export const TRACE_BAR = "{TRACE_BAR}";\n')
        f.write(f'export const GRID = "{GRID_D}";\n')
        f.write(f'export const TRACE_TOP = {APEX - 20:.0f};\nexport const TRACE_BOTTOM = {BASE + 20:.0f};\n')
    print('TRACE_A =', TRACE_A[:60], '…', len(TRACE_A), 'chars')
    print('TRACE_BAR =', TRACE_BAR[:60], '…', len(TRACE_BAR), 'chars')
