import React from "react";

/**
 * Assunta brand mark: vertical sound-wave bars that together draw the letter "A",
 * on an indigo→violet rounded square. Same artwork as the app icon
 * (src-tauri/icons/source/assunta-icon.svg, generated by generate_icon.py),
 * cropped to the tile.
 */
export function AssuntaMark({ size = 32, className = "" }: { size?: number; className?: string }) {
  const id = React.useId();
  return (
    <svg
      width={size}
      height={size}
      viewBox="100 100 824 824"
      className={className}
      role="img"
      aria-label="Assunta"
    >
      <defs>
        <linearGradient id={`${id}-bg`} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor="#4F46E5" />
          <stop offset="1" stopColor="#8B5CF6" />
        </linearGradient>
      </defs>
      <rect x="100" y="100" width="824" height="824" rx="190" fill={`url(#${id}-bg)`} />
      <g fill="#FFFFFF">
        <rect x="252.0" y="660.7" width="25.5" height="116.2" rx="12.8"/>
        <rect x="293.2" y="575.0" width="25.5" height="201.9" rx="12.8"/>
        <rect x="334.4" y="491.0" width="25.5" height="213.4" rx="12.8"/>
        <rect x="375.6" y="405.3" width="25.5" height="243.1" rx="12.8"/>
        <rect x="416.8" y="319.6" width="25.5" height="213.4" rx="12.8"/>
        <rect x="416.8" y="573.4" width="25.5" height="75.0" rx="12.8"/>
        <rect x="458.0" y="238.8" width="25.5" height="210.1" rx="12.8"/>
        <rect x="458.0" y="573.4" width="25.5" height="75.0" rx="12.8"/>
        <rect x="499.2" y="238.8" width="25.5" height="124.4" rx="12.8"/>
        <rect x="499.2" y="573.4" width="25.5" height="75.0" rx="12.8"/>
        <rect x="540.4" y="238.8" width="25.5" height="210.1" rx="12.8"/>
        <rect x="540.4" y="573.4" width="25.5" height="75.0" rx="12.8"/>
        <rect x="581.6" y="319.6" width="25.5" height="213.4" rx="12.8"/>
        <rect x="581.6" y="573.4" width="25.5" height="75.0" rx="12.8"/>
        <rect x="622.8" y="405.3" width="25.5" height="243.1" rx="12.8"/>
        <rect x="664.0" y="491.0" width="25.5" height="213.4" rx="12.8"/>
        <rect x="705.2" y="575.0" width="25.5" height="201.9" rx="12.8"/>
        <rect x="746.4" y="660.7" width="25.5" height="116.2" rx="12.8"/>
      </g>
    </svg>
  );
}

/** Mark + "Assunta" wordmark. */
export function AssuntaWordmark({ size = 28, className = "" }: { size?: number; className?: string }) {
  return (
    <span className={`inline-flex items-center gap-2 ${className}`}>
      <AssuntaMark size={size} />
      <span
        className="font-semibold tracking-tight bg-gradient-to-r from-indigo-600 to-violet-500 bg-clip-text text-transparent"
        style={{ fontSize: size * 0.72 }}
      >
        Assunta
      </span>
    </span>
  );
}
