import React from "react";
import { GRID, TRACE_A, TRACE_BAR, TRACE_BOTTOM, TRACE_TOP } from "./assuntaMarkPaths";

/**
 * Assunta brand mark: an oscilloscope screen whose glowing traces draw the
 * letter "A" (a peak with ringing for the legs, a second channel's bump for the
 * crossbar). Same artwork as the app icon (src-tauri/icons/source, generated by
 * generate_icon.py), cropped to the tile.
 */
export function AssuntaMark({ size = 32, className = "" }: { size?: number; className?: string }) {
  const id = React.useId().replace(/:/g, "");
  return (
    <svg
      width={size}
      height={size}
      viewBox="100 100 824 824"
      className={className}
      role="img"
      aria-label="Assunta"
    >
      <defs>
        <radialGradient id={`${id}-screen`} cx="0.5" cy="0.45" r="0.75">
          <stop offset="0" stopColor="#111827" />
          <stop offset="1" stopColor="#03050C" />
        </radialGradient>
        <linearGradient id={`${id}-trace`} gradientUnits="userSpaceOnUse" x1="0" y1={TRACE_TOP} x2="0" y2={TRACE_BOTTOM}>
          <stop offset="0" stopColor="#22D3EE" />
          <stop offset="0.55" stopColor="#8B5CF6" />
          <stop offset="1" stopColor="#EC4899" />
        </linearGradient>
        <filter id={`${id}-glow`} x="-20%" y="-20%" width="140%" height="140%">
          <feGaussianBlur stdDeviation="14" result="blur" />
          <feMerge>
            <feMergeNode in="blur" />
            <feMergeNode in="blur" />
            <feMergeNode in="SourceGraphic" />
          </feMerge>
        </filter>
      </defs>
      <rect x="100" y="100" width="824" height="824" rx="190" fill={`url(#${id}-screen)`} />
      {/* The graticule only adds noise at small sizes */}
      {size >= 48 && <path d={GRID} stroke="#22D3EE" strokeOpacity="0.09" strokeWidth="3" fill="none" />}
      <g
        fill="none"
        stroke={`url(#${id}-trace)`}
        strokeWidth={size >= 48 ? 28 : 40}
        strokeLinecap="round"
        strokeLinejoin="round"
        filter={`url(#${id}-glow)`}
      >
        <path d={TRACE_BAR} />
        <path d={TRACE_A} />
      </g>
    </svg>
  );
}

/** Mark + "Assunta" wordmark. */
export function AssuntaWordmark({ size = 28, className = "" }: { size?: number; className?: string }) {
  return (
    <span className={`inline-flex items-center gap-2 ${className}`}>
      <AssuntaMark size={size} />
      <span
        className="font-semibold tracking-tight bg-gradient-to-r from-cyan-500 via-violet-500 to-pink-500 bg-clip-text text-transparent"
        style={{ fontSize: size * 0.72 }}
      >
        Assunta
      </span>
    </span>
  );
}
