import React from "react";
import { GRID, TRACE_A, TRACE_BAR } from "./assuntaMarkPaths";

/**
 * Assunta brand mark: an oscilloscope screen whose traces draw the letter "A" (a peak with ringing for the legs, a second channel's bump for the
 * crossbar). Same artwork as the app icon (src-tauri/icons/source, generated by
 * generate_icon.py), cropped to the tile.
 */
export function AssuntaMark({ size = 32, className = "" }: { size?: number; className?: string }) {
  const id = React.useId().replace(/:/g, "");
  return (
    <svg
      width={size}
      height={size}
      viewBox="100 100 824 824"
      className={className}
      role="img"
      aria-label="Assunta"
    >
      <defs>
        <linearGradient id={`${id}-bg`} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor="#4F46E5" />
          <stop offset="1" stopColor="#8B5CF6" />
        </linearGradient>
      </defs>
      <rect x="100" y="100" width="824" height="824" rx="190" fill={`url(#${id}-bg)`} />
      {/* The graticule only adds noise at small sizes */}
      {size >= 48 && <path d={GRID} stroke="#FFFFFF" strokeOpacity="0.12" strokeWidth="3" fill="none" />}
      <g fill="none" stroke="#FFFFFF" strokeWidth={size >= 48 ? 30 : 40} strokeLinecap="round" strokeLinejoin="round">
        <path d={TRACE_BAR} />
        <path d={TRACE_A} />
      </g>
    </svg>
  );
}

/** Mark + "Assunta" wordmark. */
export function AssuntaWordmark({ size = 28, className = "" }: { size?: number; className?: string }) {
  return (
    <span className={`inline-flex items-center gap-2 ${className}`}>
      <AssuntaMark size={size} />
      <span
        className="font-semibold tracking-tight bg-gradient-to-r from-indigo-600 to-violet-500 bg-clip-text text-transparent"
        style={{ fontSize: size * 0.72 }}
      >
        Assunta
      </span>
    </span>
  );
}
